# Generated by Django 5.1.4 on 2025-04-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uptaded_at',
            new_name='updated_at',
        ),
    ]
