# Generated by Django 5.1.4 on 2025-04-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_uptaded_at_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='No content available'),
        ),
    ]
